### ISSUE TITLE
Add a LICENSE?

### ISSUE THREAD

**Issue by 910JQK** [kerrickstaley/extracting-chinese-subs#1]
Sorry for bad English.
I'm a Chinese native. I'm going to extract the subtitles of some TV programs of Hong Kong, and attach Jyutping on them to learn Cantonese. Then I found your project. Your code works well, so I want to use a part of your code in my project. But there isn't a LICENSE. Therefore, although this is an open-source project, I can not use it, because all rights are reserved.
Could you add a license?

**Comment by kerrickstaley** [comment]
Done!

Keep in mind that this code is experimental and isn't really intended for others to directly use. It's more of an example that you can follow.

**Comment by kerrickstaley** [comment]
(I released the code under the MIT license)
